export const ROUTES = {
  HOME:               "/",
  LOGIN:              "/login",
  DASHBOARD:          "/dashboard",
  INVENTORY:          "/inventory",
  INVENTORY_ADD:      "/inventory/add",
  INVENTORY_DETAIL:   "/inventory/[id]",
  POS:                "/pos",
  RESERVATIONS:       "/reservations",
  RESERVATION_DETAIL: "/reservations/[id]",
  RESERVATION_NEW:    "/reservations/new",
  RESERVATION_TRACK:  "/reservations/track/[code]",
  SUPPLIERS:          "/suppliers",
  SUPPLIERS_ADD:      "/suppliers/add",
  SUPPLIERS_DELIVERY: "/suppliers/delivery/new",
  REPORTS:            "/reports",
  AUDIT_LOGS:         "/audit-logs",
  AI_ASSISTANT:       "/ai-assistant",
  PROFILE:            "/profile",
  SETTINGS_USERS:     "/settings/users",
};
